### ISSUE TITLE
Fine-tuned model

### ISSUE THREAD

**Issue by xiaowu0162** [ParticleMedia/RAGTruth#1]
Hi,

Thank you for the great work. Are you considering sharing the checkpoint for the fine-tuned hallucination detection model or the code to reproduce it?

Thank you very much.

**Comment by biancajiang** [comment]
Same question.

**Comment by thuwyh** [comment]
We have released the training scripts of our baseline

**Comment by thuwyh** [comment]
We have released the training scripts of our baseline
