### ISSUE TITLE
How to get the same model output?

### ISSUE THREAD

**Issue by Tomsawyerhu** [ParticleMedia/RAGTruth#6]
Congratulations to your work! We 've working on detecting hallucinations in RAG and your work has offered so much guidance.
I download llama-2-7b-chat-hf from huggingface and directly use "prompt" listed in the source_info.jsonl file,also set the temperature to be the same, however get a very different answer compared with the corresponding results in response.jsonl file. What problem could it be?

**Comment by thuwyh** [comment]
Since we generate responses with sampling, it is very hard to get exactly the same ones.
We generated the responses with TGI. Which inference tool do you use?

**Comment by Tomsawyerhu** [comment]
I try the method generate, also concatting the output token one by one, how different are these methods?

**Comment by Tomsawyerhu** [comment]
Would you mind provide some detailed params when doing sampling like top-k, top-p?
